name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel_build:
    name: Laravel Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Adjust according to the PHP version used in your Laravel project

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-progress --optimize-autoloader

      - name: Copy .env example file
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Create SQLite database file
        run: touch database/database.sqlite

      - name: Run database migrations
        run: php artisan migrate:fresh --seed

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Adjust Node.js version as needed

      - name: Install Node.js dependencies
        run: npm install # Or yarn install if using Yarn

      - name: Build Node.js assets
        run: npm run build

  laravel_test:
    name: Laravel Test
    runs-on: ubuntu-latest
    needs: laravel_build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Adjust according to the PHP version used in your Laravel project

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-progress --optimize-autoloader

      - name: Copy .env example file
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Create SQLite database file
        run: touch database/database.sqlite

      - name: Run database migrations
        run: php artisan migrate:fresh --seed

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Adjust Node.js version as needed

      - name: Install Node.js dependencies
        run: npm install # Or yarn install if using Yarn

      - name: Build Node.js assets
        run: npm run build

      - name: Run tests
        run: ./vendor/bin/phpunit

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [laravel_build, laravel_test]
    if: ${{ needs.laravel_build.result == 'success' && needs.laravel_test.result == 'success' }}
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "Proses build dan test Laravel berhasil!"

  notify_failure:
    name: Notify Failure
    runs-on: ubuntu-latest
    needs: [laravel_build, laravel_test]
    if: ${{ needs.laravel_build.result == 'failure' || needs.laravel_test.result == 'failure' }}
    steps:
      - name: Send Telegram Notification
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="Proses build atau test Laravel gagal!"
